url: http://www.hoover.ml

name: Matt Hoover | Test Engineer

collections:
  projects:
    output: true
    permalink: /:collection/:name


gems:
  - jekyll-gist
  - jekyll-redirect-from

sass:
  sass_dir: _gulp-generated-files/_sass
  style: compressed
  
exclude: ["gulpfile.js"]

permalink: /blog/:title/